#ifndef rooms_h
#define rooms_h

#include "tileRoom.h"

struct EnemyDef {
    char x;
    char y;
    Direction facing;
    byte type;
};

struct RoomDef {
    const uint8_t (*tiles)[ROOM_TILE_WIDTH];
    EnemyDef *enemies;
};


const uint8_t firstRoomTiles[ROOM_TILE_HEIGHT][ROOM_TILE_WIDTH] = {
    {STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, UNLOCKED_DOOR, UNLOCKED_DOOR, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL}
};

const RoomDef firstRoomDef = {
    firstRoomTiles,
    NULL
};

const uint8_t secondRoomTiles[ROOM_TILE_HEIGHT][ROOM_TILE_WIDTH] = {
    {STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, UNLOCKED_DOOR, UNLOCKED_DOOR, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, DIRT_FLOOR, STONE_WALL},
    {STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL}
};

const RoomDef secondRoomDef = {
    secondRoomTiles,
    NULL
};

#endif
