#ifndef rooms_h
#define rooms_h

#include "tiles.h"
#include "direction.h"

struct EnemyDef {
    const uint8_t x;
    const uint8_t y;
    const Direction facing;
    const uint8_t type;
};

struct RoomDef {
    const uint8_t (*tiles)[ROOM_TILE_WIDTH];
    const EnemyDef *enemies;
};


const uint8_t firstRoomTiles[ROOM_TILE_HEIGHT][ROOM_TILE_WIDTH] = {
    {STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR}
};

const RoomDef firstRoomDef = {
    firstRoomTiles,
    NULL
};

const uint8_t leftRoomTiles[ROOM_TILE_HEIGHT][ROOM_TILE_WIDTH] = {
    {STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL, STONE_WALL},
    {STONE_WALL, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {STONE_WALL, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {STONE_WALL, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {STONE_WALL, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {STONE_WALL, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {STONE_WALL, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {STONE_WALL, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR}
};

const RoomDef leftRoomDef = {
    leftRoomTiles,
    NULL
};


const uint8_t secondRoomTiles[ROOM_TILE_HEIGHT][ROOM_TILE_WIDTH] = {
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, DIRT_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR},
    {PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR, PLAIN_FLOOR}
};

const RoomDef secondRoomDef = {
    secondRoomTiles,
    NULL
};

#endif
